# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cristina Shaver
title_formatted: Cristina Shaver
subhead: Web Developer
email: cristina.shaver@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Howdy! I'm Cristina Shaver, a front-end web developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cristinashaver.com" # the base hostname & protocol for your site
twitter_username: cristinashaver
github_username:  cshaver

sections:
  about:
    title: About Me
    subhead: “Hello World!”
    content: >
      Galaxies from which we spring courage of our questions.
      Network of wormholes cosmic ocean rich in heavy atoms,
      of brilliant syntheses, Hypatia, white dwarf emerged into
      consciousness a billion trillion, astonishment tesseract
      billions upon billions.
  blog:
    title: Blog
    subhead: Just for fun. Projects and junk.

# Build settings
markdown: kramdown
dev: true
gems:
  - octopress-autoprefixer